# Generated by Django 2.2 on 2019-05-16 23:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tags', models.TextField(blank=True)),
                ('description', models.TextField()),
                ('project_date', models.DateTimeField(default=datetime.datetime.now)),
                ('is_published', models.BooleanField(default=True)),
                ('main_photo', models.ImageField(blank=True, upload_to='projects/%Y/%m/%d/')),
                ('opt_photo_1', models.ImageField(blank=True, upload_to='projects/%Y/%m/%d/')),
                ('opt_photo_2', models.ImageField(blank=True, upload_to='projects/%Y/%m/%d/')),
            ],
        ),
    ]
