# Generated by Django 2.2 on 2019-05-16 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='dev',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='pages.Developer'),
        ),
    ]
