# Generated by Django 2.2 on 2019-05-16 23:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20190516_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='hire_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
