# Generated by Django 2.2 on 2019-05-16 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_developer_hire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='url',
            field=models.TextField(blank=True),
        ),
    ]
