# Generated by Django 2.2 on 2019-05-17 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_developer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='linked_in',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='developer',
            name='occupation',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
