# Generated by Django 2.2 on 2019-05-17 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20190516_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='currently_available',
            field=models.BooleanField(default=True),
        ),
    ]
