# Generated by Django 2.2 on 2019-05-17 10:35

from django.db import migrations, models
import pages.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_developer_currently_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='cv',
            field=models.FileField(blank=True, upload_to='cv/%Y/%m/%d/', validators=[pages.validators.validatePdf]),
        ),
    ]
