# Generated by Django 2.2 on 2019-05-17 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_developer_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='hire_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('hire_date', models.DateTimeField(blank=True)),
                ('until_today', models.BooleanField(default=False)),
                ('end_hire_date', models.DateTimeField(blank=True)),
                ('dev', models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='pages.Developer')),
            ],
        ),
    ]
