# Generated by Django 2.2 on 2019-05-17 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20190517_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='end_hire_date',
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=255)),
                ('begin_date', models.DateTimeField(blank=True)),
                ('until_today', models.BooleanField(default=False)),
                ('end_date', models.DateTimeField(blank=True)),
                ('description', models.TextField()),
                ('dev', models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='pages.Developer')),
            ],
        ),
    ]
