# Generated by Django 2.2 on 2019-05-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20190517_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
