# Generated by Django 2.2 on 2019-05-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_work_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='hire_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='hire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
