# Generated by Django 2.2 on 2019-05-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_education_type_of_graduation'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='place',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
