# Generated by Django 2.2 on 2019-05-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_work_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='completed_projects',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='developer',
            name='finished_projects',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='developer',
            name='satisfied_clients',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
